In [1]:
import pandas as pd
import numpy as np
import glob
pd.set_option('display.max_columns', None)

In [2]:
file_list = glob.glob('stats_out/*.txt')
file_list

['stats_out/ttest_16S_N_vs_P_results.txt',
 'stats_out/fisher_Prog_culture_species_20_vs_26_results.txt',
 'stats_out/fisher_year_20_culture_genus_N_vs_P_results.txt',
 'stats_out/fisher_IPS_N_vs_P_results.txt',
 'stats_out/ttest_16S_NonProg_Year_20_vs_Year_26_results.txt',
 'stats_out/fisher_Nonprog_culture_genus_20_vs_26_results.txt',
 'stats_out/fisher_year_26_IPS_N_vs_P_results.txt',
 'stats_out/ttest_16S_Prog_Year_20_vs_Year_26_results.txt',
 'stats_out/ttest_16S_Year_20_vs_Year_26_results.txt',
 'stats_out/fisher_IPS_20_vs_26_results.txt',
 'stats_out/fisher_culture_species_N_vs_P_results.txt',
 'stats_out/ttest_16S_Year_20_N_vs_P_results.txt',
 'stats_out/fisher_26_year_mgx_genus_N_vs_P_results.txt',
 'stats_out/fisher_year_20_IPS_N_vs_P_results.txt',
 'stats_out/fisher_Nonprog_mgx_genus_20_vs_26_results.txt',
 'stats_out/fisher_Prog_culture_genus_20_vs_26_results.txt',
 'stats_out/ttest_16S_Year_26_N_vs_P_results.txt',
 'stats_out/fisher_mgx_genus_N_vs_P_results.txt',
 'stats_out/fisher_Nonprog_IPS_20_vs_26_results.txt',
 'stats_out/fisher_mgx_species_N_vs_P_results.txt',
 'stats_out/fisher_culture_genus_20_vs_26_results.txt',
 'stats_out/fisher_26_year_mgx_species_N_vs_P_results.txt',
 'stats_out/fisher_year_26_culture_genus_N_vs_P_results.txt',
 'stats_out/fisher_year_20_culture_species_N_vs_P_results.txt',
 'stats_out/fisher_culture_species_20_vs_26_results.txt',
 'stats_out/fisher_year_26_culture_species_N_vs_P_results.txt',
 'stats_out/fisher_culture_genus_N_vs_P_results.txt',
 'stats_out/fisher_20_year_mgx_species_N_vs_P_results.txt',
 'stats_out/fisher_Prog_mgx_genus_20_vs_26_results.txt',
 'stats_out/fisher_Nonprog_mgx_species_20_vs_26_results.txt',
 'stats_out/fisher_Nonprog_culture_species_20_vs_26_results.txt',
 'stats_out/fisher_Prog_IPS_20_vs_26_results.txt',
 'stats_out/fisher_mgx_species_20_vs_26_results.txt',
 'stats_out/fisher_Prog_mgx_species_20_vs_26_results.txt',
 'stats_out/fisher_20_year_mgx_genus_N_vs_P_results.txt',
 'stats_out/fisher_mgx_genus_20_vs_26_results.txt']

In [3]:
###genus level

In [28]:
#P vs N - 20 + 26 years
df_mgx = pd.read_csv('stats_out/fisher_mgx_genus_N_vs_P_results.txt', sep = '\t')
df_culture =  pd.read_csv('stats_out/fisher_culture_genus_N_vs_P_results.txt', sep = '\t')
df_16s = pd.read_csv('stats_out/ttest_16S_N_vs_P_results.txt', sep = '\t')

dfm = pd.merge(df_mgx, df_culture, on = 'otu', how = 'outer', suffixes=('_mgx', '_culture'))

dfm = pd.merge(dfm, df_16s, left_on = 'otu', right_on = 'genus', how = 'outer', suffixes=('', '_16S'))

filter_value = 0.05

dfm = dfm[
    (dfm['P-value_mgx'] <= filter_value) &
    (dfm['P-value_culture'] <= filter_value) &
    (dfm['P-value'] <= filter_value)
]

dfm

Empty DataFrame
Columns: [otu, Odds_Ratio_mgx, P-value_mgx, N_pos_mgx, N_neg_mgx, P_pos_mgx, P_neg_mgx, FDR_BH_mgx, Odds_Ratio_culture, P-value_culture, N_pos_culture, N_neg_culture, P_pos_culture, P_neg_culture, FDR_BH_culture, otu_16S, T-stat, P-value, N_mean, N_std, N_n, P_mean, P_std, P_n, FDR_BH, genus]
Index: []

In [29]:
#P vs N - 20 years
df_mgx = pd.read_csv('stats_out/fisher_20_year_mgx_genus_N_vs_P_results.txt', sep = '\t')
df_culture =  pd.read_csv('stats_out/fisher_year_20_culture_genus_N_vs_P_results.txt', sep = '\t')
df_16s = pd.read_csv('stats_out/ttest_16S_Year_20_N_vs_P_results.txt', sep = '\t')

dfm = pd.merge(df_mgx, df_culture, on = 'otu', how = 'outer', suffixes=('_mgx', '_culture'))

dfm = pd.merge(dfm, df_16s, left_on = 'otu', right_on = 'genus', how = 'outer', suffixes=('', '_16S'))

filter_value = 0.05

dfm = dfm[
    (dfm['P-value_mgx'] <= filter_value) &
    (dfm['P-value_culture'] <= filter_value) &
    (dfm['P-value'] <= filter_value)
]

dfm

Empty DataFrame
Columns: [otu, Odds_Ratio_mgx, P-value_mgx, N_pos_mgx, N_neg_mgx, P_pos_mgx, P_neg_mgx, FDR_BH_mgx, Odds_Ratio_culture, P-value_culture, N_pos_culture, N_neg_culture, P_pos_culture, P_neg_culture, FDR_BH_culture, otu_16S, T-stat, P-value, N_mean, N_std, N_n, P_mean, P_std, P_n, FDR_BH, genus]
Index: []

In [30]:
#P vs N - 26 years
df_mgx = pd.read_csv('stats_out/fisher_26_year_mgx_genus_N_vs_P_results.txt', sep = '\t')
df_culture =  pd.read_csv('stats_out/fisher_year_26_culture_genus_N_vs_P_results.txt', sep = '\t')
df_16s = pd.read_csv('stats_out/ttest_16S_Year_26_N_vs_P_results.txt', sep = '\t')

dfm = pd.merge(df_mgx, df_culture, on = 'otu', how = 'outer', suffixes=('_mgx', '_culture'))

dfm = pd.merge(dfm, df_16s, left_on = 'otu', right_on = 'genus', how = 'outer', suffixes=('', '_16S'))

filter_value = 0.05

dfm = dfm[
    (dfm['P-value_mgx'] <= filter_value) &
    (dfm['P-value_culture'] <= filter_value) &
    (dfm['P-value'] <= filter_value)
]

dfm

Empty DataFrame
Columns: [otu, Odds_Ratio_mgx, P-value_mgx, N_pos_mgx, N_neg_mgx, P_pos_mgx, P_neg_mgx, FDR_BH_mgx, Odds_Ratio_culture, P-value_culture, N_pos_culture, N_neg_culture, P_pos_culture, P_neg_culture, FDR_BH_culture, otu_16S, T-stat, P-value, N_mean, N_std, N_n, P_mean, P_std, P_n, FDR_BH, genus]
Index: []

In [31]:
# 20 vs 26 years - N + P
df_mgx = pd.read_csv('stats_out/fisher_mgx_genus_20_vs_26_results.txt', sep = '\t')
df_culture =  pd.read_csv('stats_out/fisher_culture_genus_20_vs_26_results.txt', sep = '\t')
df_16s = pd.read_csv('stats_out/ttest_16S_Year_20_vs_Year_26_results.txt', sep = '\t')

dfm = pd.merge(df_mgx, df_culture, on = 'otu', how = 'outer', suffixes=('_mgx', '_culture'))

dfm = pd.merge(dfm, df_16s, left_on = 'otu', right_on = 'genus', how = 'outer', suffixes=('', '_16S'))

filter_value = 0.05

dfm = dfm[
    (dfm['P-value_mgx'] <= filter_value) &
    (dfm['P-value_culture'] <= filter_value) &
    (dfm['P-value'] <= filter_value)
]

dfm

,otu,Odds_Ratio_mgx,P-value_mgx,20_pos_mgx,20_neg_mgx,26_pos_mgx,26_neg_mgx,FDR_BH_mgx,Odds_Ratio_culture,P-value_culture,20_pos_culture,20_neg_culture,26_pos_culture,26_neg_culture,FDR_BH_culture,otu_16S,T-stat,P-value,Year_20_mean,Year_20_std,Year_20_n,Year_26_mean,Year_26_std,Year_26_n,FDR_BH,genus
81,Brevundimonas,7.000000,0.004555,14.0,22.0,3.0,33.0,0.246450,inf,5.124295e-04,11.0,37.0,0.0,47.0,0.006149,k__Pseudomonadati|p__Pseudomonadota|c__Alphapr...,3.294558,0.001630,1.284702,3.009283,44.0,-0.376846,1.461370,44.0,0.033369,Brevundimonas
179,Enterobacter,15.000000,0.000001,27.0,9.0,6.0,30.0,0.000560,inf,2.587043e-03,9.0,39.0,0.0,47.0,0.022175,k__Pseudomonadati|p__Pseudomonadota|c__Gammapr...,2.160995,0.033920,6.433040,1.971051,44.0,5.263248,3.001367,44.0,0.231489,Enterobacter
237,Helicobacter,0.085714,0.013589,1.0,35.0,9.0,27.0,0.565520,2.842809,2.111641e-02,25.0,23.0,13.0,34.0,0.115180,k__Pseudomonadati|p__Campylobacterota|c__Epsil...,3.142587,0.002305,9.962832,3.438575,44.0,7.528948,3.816874,44.0,0.042698,Helicobacter
257,Klebsiella,4.200000,0.008046,21.0,15.0,9.0,27.0,0.362751,11.250000,4.027686e-04,16.0,32.0,2.0,45.0,0.006042,k__Pseudomonadati|p__Pseudomonadota|c__Gammapr...,4.873701,0.000005,4.786925,3.229667,44.0,1.607958,2.879114,44.0,0.000490,Klebsiella
422,Pseudomonas,5.547368,0.004290,17.0,19.0,5.0,31.0,0.246450,17.085714,8.142945e-04,13.0,35.0,1.0,46.0,0.008143,k__Pseudomonadati|p__Pseudomonadota|c__Gammapr...,3.252525,0.001720,8.530628,1.910977,44.0,6.830250,2.893727,44.0,0.033452,Pseudomonas
470,Serratia,7.857143,0.000221,22.0,14.0,6.0,30.0,0.029873,24.456522,1.362518e-07,25.0,23.0,2.0,45.0,0.000003,k__Pseudomonadati|p__Pseudomonadota|c__Gammapr...,2.930594,0.004346,4.590954,3.381296,44.0,2.593102,3.002609,44.0,0.062619,Serratia
494,Stenotrophomonas,16.000000,0.000002,24.0,12.0,4.0,32.0,0.000560,20.533333,4.142065e-08,28.0,20.0,3.0,44.0,0.000002,k__Pseudomonadati|p__Pseudomonadota|c__Gammapr...,4.444878,0.000029,5.109429,3.826777,44.0,1.970757,2.700956,44.0,0.002255,Stenotrophomonas

In [32]:
# 20 vs 26 years - N
df_mgx = pd.read_csv('stats_out/fisher_Nonprog_mgx_genus_20_vs_26_results.txt', sep = '\t')
df_culture =  pd.read_csv('stats_out/fisher_Nonprog_culture_genus_20_vs_26_results.txt', sep = '\t')
df_16s = pd.read_csv('stats_out/ttest_16S_NonProg_Year_20_vs_Year_26_results.txt', sep = '\t')

dfm = pd.merge(df_mgx, df_culture, on = 'otu', how = 'outer', suffixes=('_mgx', '_culture'))

dfm = pd.merge(dfm, df_16s, left_on = 'otu', right_on = 'genus', how = 'outer', suffixes=('', '_16S'))

filter_value = 0.05

dfm = dfm[
    (dfm['P-value_mgx'] <= filter_value) &
    (dfm['P-value_culture'] <= filter_value) &
    (dfm['P-value'] <= filter_value)
]

dfm

,otu,Odds_Ratio_mgx,P-value_mgx,20_pos_mgx,20_neg_mgx,26_pos_mgx,26_neg_mgx,FDR_BH_mgx,Odds_Ratio_culture,P-value_culture,20_pos_culture,20_neg_culture,26_pos_culture,26_neg_culture,FDR_BH_culture,otu_16S,T-stat,P-value,Year_20_mean,Year_20_std,Year_20_n,Year_26_mean,Year_26_std,Year_26_n,FDR_BH,genus
380,Stenotrophomonas,20.8,0.000491,13.0,5.0,2.0,16.0,0.201292,12.458333,0.001488,13.0,12.0,2.0,23.0,0.025795,k__Pseudomonadati|p__Pseudomonadota|c__Gammapr...,3.286363,0.002091,5.325262,3.647683,22.0,1.983945,3.07186,22.0,0.095579,Stenotrophomonas

In [33]:
# 20 vs 26 years - P
df_mgx = pd.read_csv('stats_out/fisher_Prog_mgx_genus_20_vs_26_results.txt', sep = '\t')
df_culture =  pd.read_csv('stats_out/fisher_Prog_culture_genus_20_vs_26_results.txt', sep = '\t')
df_16s = pd.read_csv('stats_out/ttest_16S_Prog_Year_20_vs_Year_26_results.txt', sep = '\t')

dfm = pd.merge(df_mgx, df_culture, on = 'otu', how = 'outer', suffixes=('_mgx', '_culture'))

dfm = pd.merge(dfm, df_16s, left_on = 'otu', right_on = 'genus', how = 'outer', suffixes=('', '_16S'))

filter_value = 0.05

dfm = dfm[
    (dfm['P-value_mgx'] <= filter_value) &
    (dfm['P-value_culture'] <= filter_value) &
    (dfm['P-value'] <= filter_value)
]

dfm

,otu,Odds_Ratio_mgx,P-value_mgx,20_pos_mgx,20_neg_mgx,26_pos_mgx,26_neg_mgx,FDR_BH_mgx,Odds_Ratio_culture,P-value_culture,20_pos_culture,20_neg_culture,26_pos_culture,26_neg_culture,FDR_BH_culture,otu_16S,T-stat,P-value,Year_20_mean,Year_20_std,Year_20_n,Year_26_mean,Year_26_std,Year_26_n,FDR_BH,genus
157,Klebsiella,5.500000,0.040912,11.0,7.0,4.0,14.0,0.802273,13.500,0.009783,9.0,14.0,1.0,21.0,0.105167,k__Pseudomonadati|p__Pseudomonadota|c__Gammapr...,3.516263,0.001068,4.837459,3.157675,22.0,1.599251,2.947419,22.0,0.207772,Klebsiella
318,Stenotrophomonas,12.571429,0.004511,11.0,7.0,2.0,16.0,0.227475,39.375,0.000023,15.0,8.0,1.0,21.0,0.000999,k__Pseudomonadati|p__Pseudomonadota|c__Gammapr...,2.930460,0.006050,4.893595,4.072174,22.0,1.957570,2.345427,22.0,0.277556,Stenotrophomonas

In [34]:
###species level

In [35]:
#P vs N - 20 + 26 years
df_mgx = pd.read_csv('stats_out/fisher_mgx_species_N_vs_P_results.txt', sep = '\t')
df_culture =  pd.read_csv('stats_out/fisher_culture_species_N_vs_P_results.txt', sep = '\t')


dfm = pd.merge(df_mgx, df_culture, on = 'otu', how = 'outer', suffixes=('_mgx', '_culture'))


filter_value = 0.05

dfm = dfm[
    (dfm['P-value_mgx'] <= filter_value) &
    (dfm['P-value_culture'] <= filter_value)
]

dfm['otu']

Series([], Name: otu, dtype: object)

In [36]:
#P vs N - 20 years
df_mgx = pd.read_csv('stats_out/fisher_20_year_mgx_species_N_vs_P_results.txt', sep = '\t')
df_culture =  pd.read_csv('stats_out/fisher_year_20_culture_species_N_vs_P_results.txt', sep = '\t')

dfm = pd.merge(df_mgx, df_culture, on = 'otu', how = 'outer', suffixes=('_mgx', '_culture'))


filter_value = 0.05

dfm = dfm[
    (dfm['P-value_mgx'] <= filter_value) &
    (dfm['P-value_culture'] <= filter_value) 
]

dfm

Empty DataFrame
Columns: [otu, Odds_Ratio_mgx, P-value_mgx, N_pos_mgx, N_neg_mgx, P_pos_mgx, P_neg_mgx, FDR_BH_mgx, Odds_Ratio_culture, P-value_culture, N_pos_culture, N_neg_culture, P_pos_culture, P_neg_culture, FDR_BH_culture]
Index: []

In [37]:
#P vs N - 26 years
df_mgx = pd.read_csv('stats_out/fisher_26_year_mgx_species_N_vs_P_results.txt', sep = '\t')
df_culture =  pd.read_csv('stats_out/fisher_year_26_culture_species_N_vs_P_results.txt', sep = '\t')

dfm = pd.merge(df_mgx, df_culture, on = 'otu', how = 'outer', suffixes=('_mgx', '_culture'))


filter_value = 0.05

dfm = dfm[
    (dfm['P-value_mgx'] <= filter_value) &
    (dfm['P-value_culture'] <= filter_value)
]

dfm

Empty DataFrame
Columns: [otu, Odds_Ratio_mgx, P-value_mgx, N_pos_mgx, N_neg_mgx, P_pos_mgx, P_neg_mgx, FDR_BH_mgx, Odds_Ratio_culture, P-value_culture, N_pos_culture, N_neg_culture, P_pos_culture, P_neg_culture, FDR_BH_culture]
Index: []

In [38]:
# 20 vs 26 years - N + P
df_mgx = pd.read_csv('stats_out/fisher_mgx_species_20_vs_26_results.txt', sep = '\t')
df_culture =  pd.read_csv('stats_out/fisher_culture_species_20_vs_26_results.txt', sep = '\t')

dfm = pd.merge(df_mgx, df_culture, on = 'otu', how = 'outer', suffixes=('_mgx', '_culture'))


filter_value = 0.05

dfm = dfm[
    (dfm['P-value_mgx'] <= filter_value) &
    (dfm['P-value_culture'] <= filter_value)
]

dfm

,otu,Odds_Ratio_mgx,P-value_mgx,20_pos_mgx,20_neg_mgx,26_pos_mgx,26_neg_mgx,FDR_BH_mgx,Odds_Ratio_culture,P-value_culture,20_pos_culture,20_neg_culture,26_pos_culture,26_neg_culture,FDR_BH_culture
263,Brevundimonas diminuta,10.818182,0.001263,14.0,22.0,2.0,34.0,0.099948,inf,5.124295e-04,11.0,37.0,0.0,47.0,0.018550
502,Enterobacter mori,17.000000,0.000039,18.0,18.0,2.0,34.0,0.011222,inf,2.647437e-02,6.0,42.0,0.0,47.0,0.319457
519,Enterococcus casseliflavus,6.538462,0.023825,10.0,26.0,2.0,34.0,0.563756,inf,5.691495e-03,8.0,40.0,0.0,47.0,0.103016
522,Enterococcus faecalis,3.352941,0.028731,27.0,9.0,17.0,19.0,0.602654,14.741379,3.539180e-05,19.0,29.0,2.0,45.0,0.003203
706,Helicobacter pylori,0.100000,0.027810,1.0,35.0,8.0,28.0,0.602654,2.842809,2.111641e-02,25.0,23.0,13.0,34.0,0.294005
1171,Pseudomonas aeruginosa,12.142857,0.000557,15.0,21.0,2.0,34.0,0.057090,12.105263,7.632503e-03,10.0,38.0,1.0,46.0,0.115124
1266,Raoultella terrigena,8.000000,0.000671,18.0,18.0,4.0,32.0,0.064879,12.105263,7.632503e-03,10.0,38.0,1.0,46.0,0.115124
1293,Rothia dentocariosa,0.314286,0.032054,11.0,25.0,21.0,15.0,0.641442,0.340081,2.532840e-02,9.0,39.0,19.0,28.0,0.319457
1317,Schaalia odontolytica,0.318182,0.032899,14.0,22.0,24.0,12.0,0.650886,0.279412,3.818941e-03,14.0,34.0,28.0,19.0,0.098747
1346,Serratia marcescens,8.680000,0.000170,21.0,15.0,5.0,31.0,0.026844,23.000000,7.218218e-05,16.0,32.0,1.0,46.0,0.004355
1351,Serratia quinivorans,10.000000,0.027810,8.0,28.0,1.0,35.0,0.602654,20.909091,1.652885e-04,15.0,33.0,1.0,46.0,0.007479
1456,Stenotrophomonas maltophilia,16.000000,0.000002,24.0,12.0,4.0,32.0,0.003603,18.857143,1.180491e-07,27.0,21.0,3.0,44.0,0.000021

In [39]:
# 20 vs 26 years - N
df_mgx = pd.read_csv('stats_out/fisher_Nonprog_mgx_species_20_vs_26_results.txt', sep = '\t')
df_culture =  pd.read_csv('stats_out/fisher_Nonprog_culture_species_20_vs_26_results.txt', sep = '\t')

dfm = pd.merge(df_mgx, df_culture, on = 'otu', how = 'outer', suffixes=('_mgx', '_culture'))


filter_value = 0.05

dfm = dfm[
    (dfm['P-value_mgx'] <= filter_value) &
    (dfm['P-value_culture'] <= filter_value) 
]

dfm

,otu,Odds_Ratio_mgx,P-value_mgx,20_pos_mgx,20_neg_mgx,26_pos_mgx,26_neg_mgx,FDR_BH_mgx,Odds_Ratio_culture,P-value_culture,20_pos_culture,20_neg_culture,26_pos_culture,26_neg_culture,FDR_BH_culture
182,Brevundimonas diminuta,13.600000,0.017766,8.0,10.0,1.0,17.0,1.000000,inf,0.022290,6.0,19.0,0.0,25.0,0.474258
851,Pseudomonas aeruginosa,10.818182,0.040752,7.0,11.0,1.0,17.0,1.000000,9.333333,0.048797,7.0,18.0,1.0,24.0,0.717173
1055,Stenotrophomonas maltophilia,20.800000,0.000491,13.0,5.0,2.0,16.0,0.622042,12.458333,0.001488,13.0,12.0,2.0,23.0,0.212806

In [40]:
# 20 vs 26 years - P
df_mgx = pd.read_csv('stats_out/fisher_Prog_mgx_species_20_vs_26_results.txt', sep = '\t')
df_culture =  pd.read_csv('stats_out/fisher_Prog_culture_species_20_vs_26_results.txt', sep = '\t')

dfm = pd.merge(df_mgx, df_culture, on = 'otu', how = 'outer', suffixes=('_mgx', '_culture'))


filter_value = 0.05

dfm = dfm[
    (dfm['P-value_mgx'] <= filter_value) &
    (dfm['P-value_culture'] <= filter_value) 
]

dfm

,otu,Odds_Ratio_mgx,P-value_mgx,20_pos_mgx,20_neg_mgx,26_pos_mgx,26_neg_mgx,FDR_BH_mgx,Odds_Ratio_culture,P-value_culture,20_pos_culture,20_neg_culture,26_pos_culture,26_neg_culture,FDR_BH_culture
804,Schaalia odontolytica,0.142857,0.017592,6.0,12.0,14.0,4.0,0.422467,0.192308,0.015550,5.0,18.0,13.0,9.0,0.370097
820,Serratia marcescens,26.714286,0.000945,11.0,7.0,1.0,17.0,0.124636,inf,0.009161,7.0,16.0,0.0,22.0,0.272526
879,Stenotrophomonas maltophilia,12.571429,0.004511,11.0,7.0,2.0,16.0,0.244938,32.666667,0.000075,14.0,9.0,1.0,21.0,0.008969